spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

